language: python
python:
- "3.5"
env:
  global:
    secure: CR0RYDzX5o+Jwd7wAE4XES8Gwpk6X9JbRREb7dFhfUgXoW1gLOlRlz5lI9CtXw4ib/XtYvm3gcpJADn63S+X2edVt5loQcB7wH8LhPYfdkhmDm+DUpugq4TZnWjkeYKkOQpu7l65dKCfO9nnXiuzZlJ4jIW7vhh3IPmHLUWUzAw=
services:
- docker    
install:
- docker pull peragro/peragro-at 
- docker build -t peragro/peragro-at . --build-arg CACHEBUST=$(date +%s)
script:
- docker run --rm -it peragro/peragro-at /bin/bash -c "nosetests -v --with-xunit --xunit-file=nosetests.xml --cover-package=damn_at --with-coverage -e ^rtest.+$ --cover-erase --cover-xml --all-modules -w /opt/peragro-at/tests/"
after_script:
- docker run --rm -it peragro/peragro-at /bin/bash -c "/opt/peragro-at/bin/update-gh-pages.sh"
after_success:
  docker run --rm -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -it peragro/peragro-at /bin/bash -c "coveralls -b /opt/peragro-at/"
