language: python
python:
- "3.5"
env:
  global:
  - secure: "PjRj++G3b5AkLUowfqxx6ZPyo7e9qOfYuM4GX8iW3QLoKYv6Bs9N+jU40Hbr3kwmK6fA/ZmGfajp7N2lqfQfRdoFz9aATIxU2zr1HCQ+wlUtasRsyrbhdmGjRC3aAGvHponELSGZ+HxO4LG6X3e9yjAtH5kYwuVF1vsXmnGTcLk="
before_install:
- sudo apt-get install -qq python-sphinx
services:
- docker    
install:
- docker pull peragro/peragro-at 
- docker build -t peragro/peragro-at . --build-arg CACHEBUST=$(date +%s) --cache-from peragro/peragro-at
script:
- docker run --rm -it peragro/peragro-at /bin/bash -c "nosetests -v --with-xunit --xunit-file=nosetests.xml --cover-package=damn_at --with-coverage -e ^rtest.+$ --cover-erase --cover-xml --all-modules -w /opt/peragro-at/tests/"
after_script:
- ./bin/deploy.sh
after_success:
- docker run --rm -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -it peragro/peragro-at /bin/bash -c "coveralls -b /opt/peragro-at/"